// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://irxsnjdfyskpvcepgzlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlyeHNuamRmeXNrcHZjZXBnemx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM4Mjk1NjEsImV4cCI6MjA0OTQwNTU2MX0.bo704T3fHMWZwVNZk6UFpYU0qy36Ve6ABcVTFwLPPZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);